### ISSUE TITLE
Adding a live link

### ISSUE THREAD

**Issue by ghost** [sarthakkundra/Pig-Game#2]
@sarthakkundra this is a beautiful project. Im here from reading your article on dev.to would it be possible to add a live link to the project? That way someone can easily see the final product

**Comment by sarthakkundra** [comment]
@KarenEfereyan Thanks! Actually this project was part of a JavaScript course. So, I think it wouldn't be fair to add a live link to it without changing somethings in it first. If you feel like you want to do some UI changes feel free to open an issue regarding that.

**Comment by ghost** [comment]
how do I make UI changes when I don't know how the UI looks? Never mind I
can always make a fork of the project right?

**Comment by sarthakkundra** [comment]
Yeah sure. Go ahead
